{{- if .Values.ingress.enabled -}}
{{- $fullName := include "helm-guestbook.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.18-0" .Capabilities.KubeVersion.Version -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
spec:
  rules:
  - host: guestbook2.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ $fullName }}
            port:
              number: {{ $svcPort }}
{{- end }}              
