clusterK8s:
  name: "k8s-lab"
  server: https://kubernetes.default.svc
  source: https://github.com/ederqueirozdf/lab-apps2.git
 

argocd:
  namespace: argocd-2
  disablePrune: false
  apps:
    - name: "guestbook2"
      finalizers: []
      labels: []
        # - key: chave
        #   value: valor
      annotations: []
        # - key: chave
        #   value: valor
      spec:
        project: k8s-lab
        source:
          path: guestbook
          repoURL: https://github.com/ederqueirozdf/lab-apps2.git
          targetRevision: HEAD
        destination:
        #   namespace: infra
          server: https://kubernetes.default.svc
        # syncPolicy:
        #   automated:
        #     prune: true
        #     selfHeal: true

#####################################################################
# ------- THANOS 
#####################################################################

    - name: "thanos"
      finalizers: []
      labels: []
        # - key: chave
        #   value: valor
      annotations: []
        # - key: chave
        #   value: valor
      spec:
        project: k8s-lab
        source:
          path: thanos
          repoURL: https://github.com/ederqueirozdf/lab-apps2.git
          targetRevision: HEAD
        destination:
        #   namespace: infra
          server: https://kubernetes.default.svc
        # syncPolicy:
        #   automated:
        #     prune: true
        #     selfHeal: true        