clusterK8s:
  name: "k8s-lab"
  server: https://kubernetes.default.svc
  source: https://github.com/ederqueirozdf/lab-apps2.git
  extraApi: 
    - namespace: "*"
      server: https://kubernetes.default.svc  

argocd:
  namespace: argocd-2
  disablePrune: false

# #####################################################################
# APLICs
# #####################################################################

  apps:
    - name: "k8s-lab-apps"
      finalizers:
      - resources-finalizer.argocd.argoproj.io
      labels: []
        # - key: chave
        #   value: valor
      annotations: []
        # - key: chave
        #   value: valor
      spec:
        project: default
        source:
          path: apps
          repoURL: https://github.com/ederqueirozdf/lab-apps2.git
          targetRevision: HEAD 
        destination:
          namespace: default
          name: in-cluster
        syncPolicy:
          automated:
            prune: true
            selfHeal: true

# #####################################################################
# MONITOR
# #####################################################################

  apps:
    - name: "thanos"
      finalizers: []
      labels: []
        # - key: chave
        #   value: valor
      annotations: []
        # - key: chave
        #   value: valor
      spec:
        project: k8s-lab
        source:
          path: aplic/thanos
          repoURL: https://github.com/ederqueirozdf/lab-apps2.git
          targetRevision: HEAD
          helm:
            valueFiles:
              - values.yaml          
        destination:
          namespace: thanos
          server: https://kubernetes.default.svc
        syncPolicy:
          automated:
            prune: true
            selfHeal: true